version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hangman_db
    environment:
      POSTGRES_USER: raif
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hangmandb
    ports:
      - "5432:5432"
    volumes:
      - hangman_data:/var/lib/postgresql/data

volumes:
  hangman_data: