# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hangmandb
spring.datasource.username=raif
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# App name
spring.application.name=hangman-api